# Generated by Django 4.1.7 on 2023-03-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studinfo',
            name='acc_balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studinfo',
            name='statement',
            field=models.FileField(default=1663, upload_to='uploads'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studinfo',
            name='lattempt',
            field=models.IntegerField(default=0),
        ),
    ]
